### PR TITLE
Revert "Fix styling"

### PR DESCRIPTION
**Pull request by brandenHusted**
Reverts calvin-cs262-fall2023-teamA/client#36
The submit button is broken.

### CODE REVIEW

**Comment by harryg02** [comment]
are you sure that the problem can be fixed if you revert it?

**Comment by brandenHusted** [comment]
I believe so because it was caused by that pull request. I like the look of everything just the submit button doesn't work

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by harryg02** [comment]
Did that button work previously?

**Comment by brandenHusted** [comment]
Yes, it sent you to the main page although it won't do that it saids you need a title even when you have one. Probably could be fixed easily

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by harryg02** [comment]
I just fixed it in the main branch, you can double check that and close this pull request

**Comment by StevenM-Calvin** [comment]
just tested, submit button works now.

**Pull request closed without merging**
