### PR TITLE
Feature/addPageFunctionality

### PR DESCRIPTION
**Pull request by StevenM-Calvin**
Adds input fields (textInput, dropdowns, switches) to the add page. Also implements useStates to store the user input. 

This input is not currently sent to another screen or the database. I plan to work on getting the information sent to our database later this week.

Other small changes are also made. On the login screen, the first letter of a word is no longer capitalized. On the main screen, the "popup" modal has been changed to an alert().

### CODE REVIEW

**Comment by Aish-warya-Joshi** [comment]
The search and add page icons were not visible for some reason. Also, we might not need the 'Jewelry' category since we already have 'clothing/accessories'. Other than that, looks good.

**Comment by StevenM-Calvin** [comment]
If you press on the search icon when you first load the main page, the add button and profile icon should appear. That is currently a bug in main.

**Comment by StevenM-Calvin** [comment]
I'll make an additional pull request (and merge it without approval since it's such a small change) later to remove the jewelry category.

**Comment by StevenM-Calvin** [comment]
> If you press on the search icon when you first load the main page, the add button and profile icon should appear. That is currently a bug in main.

For reference, this was a bug from a branch that was merged earlier today ("mainPageStyleing"). I just planned on it being fixed at a later point.

**Comment by Aish-warya-Joshi** [comment]
okay! I'll merge this one then

**Review by Aish-warya-Joshi — APPROVED** [review]

**Pull request merged**
